# .github/workflows/deploy.yml
name: Build and Deploy Angular

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build -- --configuration production
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/todolist/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist/todolist/browser
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: TodolistCICD
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist/todolist/browser
